name: Compilation LaTeX - PrÃ©sentations
on:
  workflow_dispatch: # Permet le lancement manuel

jobs:
  load_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load matrix from JSON and filter presentations
        id: set-matrix
        run: |
          set -e
          # Filter only files with presentation: true
          matrix=$(cat matrix.json | jq -c '{include: [.files[] | select(.presentation == true)]}')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  Produce_LaTeX_document:
    needs: load_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.load_matrix.outputs.matrix) }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Check encoding
        run: file -i ${{ matrix.file }}.tex

      - name: Compilation ${{ matrix.file }}
        uses: xu-cheng/latex-action@v4
        with:
          #latexmk_use_lualatex: true
          args: -file-line-error -halt-on-error -interaction=nonstopmode -recorder -usepretex="\\newcommand{\\activeranimations}{}"
          root_file: ${{ matrix.file }}.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF-${{ matrix.file }}.pdf
          path: ${{ matrix.file }}.pdf

